version: '3'
services:
  client:
    image: phurti_game:0.1
    container_name: phurti_game
    build:
      context: ./game
      dockerfile: Dockerfile
    volumes:
      - ./game:/home/node/src
    ports:
      - 3000:3000
    environment:
      - REACT_APP_SERVER_PORT=80
    expose:
      - 3000
    command: bash -c "rm -rf node_modules && npm install && npm run start && bash"
    stdin_open: true
    tty: true
  server:
    image: phurti_server:0.1
    container_name: phurti_server
    build:
      context: ./server
      dockerfile: Dockerfile
    command: bash -c "rm -rf node_modules && npm install && npm run dev && bash"
    volumes:
      - ./server:/home/http_server_user/src
    ports:
      - 80:8000
    environment:
      - PORT=8000
    expose:
      - 8000
    stdin_open: true
    tty: true
